version: '3'
services:
  node_alice:
    image: parity/substrate
    volumes:
      - './tmp/node_alice:/mnt/node'
      - './genesis/:/mnt/genesis:ro'
    networks:
      testnet:
        aliases:
          - node_alice
    command:
      - --chain=/mnt/genesis/local_testnet.json
      - --base-path=/mnt/node
      - --alice
      - --node-key=0000000000000000000000000000000000000000000000000000000000000001
      - --validator
      - --ws-external
      - --rpc-external
      - --telemetry-url=ws://telemetry.polkadot.io:1024
    ports:
      - '9933:9933'
      - '9944:9944'
      - '30333:30333'
  node_bob:
    image: parity/substrate
    volumes:
      - './tmp/node_bob:/mnt/node'
      - './genesis/:/mnt/genesis:ro'
    networks:
      testnet:
        aliases:
          - node_bob
    command:
      - --chain=/mnt/genesis/local_testnet.json
      - --base-path=/mnt/node
      - --bob
      - --validator
      - --ws-external
      - --rpc-external
      - --telemetry-url=ws://telemetry.polkadot.io:1024
    # ports:
    #   - '9934:9933'
    #   - '9945:9944'
    #   - '30334:30333'
  polkadot-ui:
    image: centrifugeio/polkadot-ui
    networks:
      testnet:
        aliases:
          - polkadot_ui
    ports:
      - '3000:80'
  e2e:
    build:
      context: .
      dockerfile: Dockerfile.integration
    ports:
      - '8080:8080'
    networks:
      testnet:
        aliases:
          - polkadot_ui
    volumes:
      - './tmp/e2e:/mnt/app'
      - './tmp/media:/mnt/media'
    # command: ['wait_for_it.sh', 'node_alice:9944', '--', 'npm', 'run', 'test']
    # command: ['npm', 'run', 'test']
    command: ['npm', 'start']
volumes:
  node_alice:
  node_bob:
  polkadot-ui:
  e2e:
networks:
  testnet:
    external:
      name: standalone
