FROM node:13.1.0-alpine

# RUN apt-get -q update && apt-get -qy install netcat
# RUN git clone git@github.com:vishnubob/wait-for-it.git

WORKDIR /usr/app

COPY package.json .
RUN npm install

COPY . .
COPY ./scripts/wait-for-it.sh wait-for-it.sh

RUN chmod +x wait-for-it.sh

ENTRYPOINT [ "/bin/bash", "-c" ]

# CMD ["./wait-for-it.sh" , "[ENTER YOUR ENDPOINT HERE]" , "--strict" , "--timeout=300" , "--" , "YOUR REAL START COMMAND"]

CMD ["npm", "run", "test"]

