version: '3'
services:
  node_alice:
    container_name: node_alice
    image: parity/substrate

    volumes:
      - './tmp/node_alice:/mnt/node'
      - './genesis/:/mnt/genesis:ro'
    command:
      # - --chain=/mnt/genesis/local_testnet.json
      - --chain=dev
      - --base-path=/mnt/node
      - --alice
      - --validator
      - --ws-external
      - --rpc-external
      - --telemetry-url=ws://telemetry.polkadot.io:1024
      - --rpc-cors=all
    ports:
      - '9933:9933'
      - '9944:9944'
      - '30333:30333'
    networks:
      - substrate_automation_testnet

  node_bob:
    container_name: node_bob
    image: parity/substrate

    volumes:
      - './tmp/node_bob:/mnt/node'
      - './genesis/:/mnt/genesis:ro'
    command:
      # - --chain=/mnt/genesis/local_testnet.json
      - --chain=dev
      - --base-path=/mnt/node
      - --bob
      - --validator
      - --ws-external
      - --rpc-external
      - --telemetry-url=ws://telemetry.polkadot.io:1024
      - --rpc-cors=all
    ports:
      - '9934:9933'
      - '9945:9944'
      - '30334:30333'
    networks:
      - substrate_automation_testnet

  polkadot_ui:
    container_name: polkadot_ui
    build:
      context: .
      dockerfile: polkadot_ui.Dockerfile
    ports:
      - '3030:80'
    networks:
      - substrate_automation_testnet

  api_test:
    container_name: api_test
    build:
      context: .
      dockerfile: integration.Dockerfile
    volumes:
      - './tmp/api_test:/mnt/app'
    networks:
      - substrate_automation_testnet
    command: ['tail', '-f', '/dev/null']

networks:
  substrate_automation_testnet:
    external:
      name: standalone
