version: '3'
services:
  node_alice:
    image: parity/substrate
    volumes:
      - './tmp/node_alice:/mnt/node'
    networks:
      # - network-a
      - internet
    command:
      - --chain=local
      - --base-path=/mnt/node
      - --alice
      - --node-key=0000000000000000000000000000000000000000000000000000000000000001
      - --validator
      - --ws-external
      - --rpc-external
      - --telemetry-url=ws://telemetry.polkadot.io:1024
    ports:
      - '9933:9933'
      - '9944:9944'
      - '30333:30333'
  node_bob:
    image: parity/substrate
    volumes:
      - './tmp/node_bob:/mnt/node'
    networks:
      # - network-a
      - internet
    command:
      - --chain=local
      - --base-path=/mnt/node
      - --bob
      - --validator
      - --ws-external
      - --rpc-external
      - --telemetry-url=ws://telemetry.polkadot.io:1024
    ports:
      - '9934:9933'
      - '9945:9944'
      - '30334:30333'
  polkadot-ui:
    image: centrifugeio/polkadot-ui
    networks:
      # - network-a
      - internet
    ports:
      - '3000:80'
    links:
      - node_alice
      - node_bob
  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    networks:
      # - network-a
      - internet
    volumes:
      - './tmp/test:/app'
    # command: ['wait_for_it.sh', 'node_alice:9944', '--', 'npm', 'run', 'test']
    command: ['./wait_for_testnet.sh']
volumes:
  node_alice:
  node_bob:
  polkadot-ui:
  test:

networks:
  # network-a:
  internet:
