version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.16.3
    steps:
      - checkout
      - restore_cache:
          keys:
            - npm-packages-v1-{{ .Branch }}-{{ checksum "package-lock.json" }}
            - npm-packages-v1-{{ .Branch }}-
            - npm-packages-v1-
      - run:
          name: Install Dependencies
          command: npm install
      - save_cache:
          paths:
            - ~/tmp/npm
          key: npm-packages-v1-{{ .Branch }}-{{ checksum "package-lock.json" }}
