version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.16.3
    steps:
      - checkout

      - restore_cache:
          keys:
            - yarn-packages-v1-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - yarn-packages-v1-{{ .Branch }}-
            - yarn-packages-v1-
      - run:
          name: Install Dependencies
          command: npm install
      - save_cache:
          paths:
            - ~/tmp/npm
          key: yarn-packages-v1-{{ .Branch }}-{{ checksum "yarn.lock" }}
      - run:
          name: Install Docker Compose
          command: ./scripts/circleci/install_docker_compose.sh
      - setup_remote_docker
      - run:
          name: Run End-to-End testing
          command: ./scripts/circleci/run_automation_test.sh -t e2e
