version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.16.3
    steps:
      - checkout

      - restore_cache:
          keys:
            - npm-packages-v1-{{ .Branch }}-{{ checksum "package-lock.json" }}
            - npm-packages-v1-{{ .Branch }}-
            - npm-packages-v1-
      - run:
          name: Install Dependencies
          command: npm install
      - save_cache:
          paths:
            - ~/tmp/npm
          key: npm-packages-v1-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run:
          name: Install Docker Compose
          command: |
            curl -L https://github.com/docker/compose/releases/download/1.19.0/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
            chmod +x ~/docker-compose
            sudo mv ~/docker-compose /usr/local/bin/docker-compose
      - setup_remote_docker
      - run:
          name: End-to-End testing
          command: |
            set -x
            docker network create --driver bridge standalone
            docker-compose up -d
            docker run $(docker ps | grep "e2e" | awk '/ / { print $2 }') npm run test:e2e
